export const INCORRECT_BODY = 'INCORRECT_BODY';
export const INCORRECT_TYPE = 'INCORRECT_TYPE';
export const MISSING_PROPERTY = 'MISSING_PROPERTY';
export const NOT_FOUND = 'NOT_FOUND';
export const INCORRECT_QUANTITY = 'INCORRECT_QUANTITY';
